buildConfiguration:
  buildCommand: npm run build:local
  installDependenciesStep:
    command: npm install
    requiredFiles:
      - package.json
      - package-lock.json
      - .npmrc
livePreviewConfiguration:
  setupCommand: "npm run dev -- --port 8080"
siteStream:
  id: site-data
  entityId: 2861414769180776896
  fields:
    - name
    - slug
  localization:
    locales:
      - en